<?php
//
// Recommended way to include parent theme styles.
// (Please see http://codex.wordpress.org/Child_Themes#How_to_Create_a_Child_Theme)
//  
add_action('wp_enqueue_scripts', 'theme_enqueue_styles', 998);

function theme_enqueue_styles() {
    wp_enqueue_style('elessi-style', get_template_directory_uri() . '/style.css');
    wp_enqueue_style('elessi-child-style', get_stylesheet_uri());
}

add_filter( 'wc_city_select_cities', 'my_cities' );
/**
 * Replace XX with the country code. Instead of YYY, ZZZ use actual  state codes.
 */
function my_cities( $cities ) {
    $cities['KE'] = array(
		'KE01' => array(
            'Mochongoi/Margat Ward',
            'Mochongoi/Ilchamus Ward',
            'Mochongoi/Mochongoi Ward',
            'Mochongoi/Mukutani Ward',
            'Mogotio/Mogotio Ward',
            'Mogotio/Emining Ward',
            'Mogotio/Kisanana',
            'Eldama Ravine/Lembus',
            'Eldama Ravine/Lembus Kwen',
            'Eldama Ravine/Ravine',
            'Eldama Ravine/Mumberers',
            'Eldama Ravine/Lembus',
            'Eldama Ravine/Koibatek'
        ),
		'KE02' => array(
            'Sotik/Sotik',
            'Sotik/Abosi',
            'Sotik/Chemagel',
            'Sotik/Kipsonoi',
            'Sotik/Kapletundo',
            'Sotik/Rongena',
            'Chepalungu/Chepalungu',
            'Chepalungu/Makimeny/Kong\'asis',
            'Chepalungu/Nyangores',
            'Chepalungu/Sigor',
            'Chepalungu/Chebunyo',
            'Chepalungu/Singiroi',
            'Bomet East/Bomet East',
            'Bomet East/Merigi',
            'Bomet East/Kembu Tegat',
            'Bomet East/Longisa',
            'Bomet East/Kipreres',
            'Bomet East/Chemaner',
            'Bomet Central/Bomet Central',
            'Bomet Central/Silibwet Township',
            'Bomet Central/Ndaraweta',
            'Bomet Central/Singorwet',
            'Bomet Central/Chesoen',
            'Bomet Central/Mutarakwa',
            'Konoin/Konoin',
            'Konoin/Chepchabas',
            'Konoin/Kimulot',
            'Konoin/Mogogosiek/Koiwo',
            'Konoin/Boito',
            'Konoin/Cheptalal/Embomos'
        ),
		'KE03' => array(
            'Mt. Elgon/Cheptais',
            'Mt. Elgon/Chesikaki',
            'Mt. Elgon/Chepyuk',
            'Mt. Elgon/Kapkateny',
            'Mt. Elgon/Elgon',
            'Mt. Elgon/Kaptama',
            'Sirisia/Namwela',
            'Sirisia/Malakisi/South Kulisiru',
            'Sirisia/Lwandanyi/North Kulisiru',
            'Kabuchai/Kabuchai',
            'Kabuchai/West Nalondo',
            'Kabuchai/Bwake',
            'Kabuchai/Mukuyuni',
            'Bumula/South Bukusu',
            'Bumula/Khasoko',
            'Bumula/Kabula',
            'Bumula/West Bukusu',
            'Bumula/Kimaeti/Napara',
            'Bumula/Bumula',
            'Bumula/Siboti',
            'Kanduyi/Bukembe West',
            'Kanduyi/Bukembe East',
            'Kanduyi/Township',
            'Kanduyi/Khalaba',
            'Kanduyi/West Sang\'alo',
            'Kanduyi/Musikoma',
            'Kanduyi/East Sangalo',
            'Kanduyi/Tuuti Marakaru',
            'Kanduyi/Marakaru',
            'Webuye/Mihuu',
            'Webuye/Ndivisi/Lugusi',
            'Webuye/Maraka',
            'Webuye West/Sitikho',
            'Webuye West/Matulo',
            'Webuye West/Bokoli',
            'Kimilili/Kibingei',
            'Kimilili/Kimili',
            'Kimilili/Maeni',
            'Kimilili/Kamukuywa',
            'Tongaren/Milima',
            'Tongaren/Mbakalo',
            'Tongaren/Naitiri/Kabuyef We',
            'Tongaren/Soysambu',
            'Tongaren/Tongaren',
            'Tongaren/Ndalu',
        ),
		'KE04' => array(
            'Teso North/Malaba Central',
            'Teso North/Malaba North',
            'Teso North/Ang\'Urai South',
            'Teso North/Ang\'Urai North',
            'Teso North/Ang\'Urai East',
            'Teso North/Malaba South',
            'Teso South/Ang\'Orom',
            'Teso South/Chakol South',
            'Teso South/Chakol North',
            'Teso South/Amukura West',
            'Teso South/Amukura East',
            'Teso South/Amukura Central',
            'Nambale/Nambale',
            'Nambale/Bukhayo North/Wal Atsi',
            'Nambale/Bukhayo East',
            'Nambale/Bukhayo Central/Lwanya Nge',
            'Matayos/Bukhayo West',
            'Matayos/Mayenye',
            'Matayos/Matayos South',
            'Matayos/Busibwabo',
            'Matayos/Burumba',
            'Butula/Marachi West',
            'Butula/Kingandole',
            'Butula/Marachi Central',
            'Butula/Marachi East',
            'Butula/Elugulu',
            'Butula/Marachi North/Esikoma',
            'Funyula/Namboboto Nambuku Ward',
            'Funyula/Bwiri',
            'Funyula/Ageng\'A Nanguba',
            'Funyula/Nangina',
            'Budalangi/Bunyala North',
            'Budalangi/Bunyala Central',
            'Budalangi/Bunyala West',
            'Budalangi/Bunyala South'
        ),
		'KE06' => array(
            'Manyatta/Nginda',
            'Manyatta/Ruguru Ngandori',
            'Manyatta/Gaturi South',
            'Manyatta/Kithimu',
            'Manyatta/Mbeti North',
            'Manyatta/Kirimari',
            'Runyenjes/Gaturi',
            'Runyenjes/Central',
            'Runyenjes/Kagaari South',
            'Runyenjes/Kieni North',
            'Runyenjes/Kieni South',
            'Gachoka/Mwea',
            'Gachoka/Makima',
            'Gachoka/Mbeti South',
            'Gachoka/Mavuria',
            'Gachoka/Kiambere',
            'Siakago/Nthanwa',
            'Siakago/Muminji',
            'Siakago/Evurore'
        ),
		'KE08' => array(
            'Kasipul/West Kasipul',
            'Kasipul/Kokech/Kowidi',
            'Kasipul/Central Kasipul',
            'Kasipul/East Kamagak',
            'Kasipul/West Kamagak',
            'Kabondo/Kabondo East',
            'Kabondo/Kabondo West',
            'Kabondo/Kokwanyo/Ka kelo',
            'Kabondo/Kojwach',
            'Karachuonyo/West Karachuonyo',
            'Karachuonyo/North Karachuonyo',
            'Karachuonyo/Central',
            'Karachuonyo/Kanyaluo',
            'Karachuonyo/Kibiri',
            'Karachuonyo/Wang\'chieng',
            'Karachuonyo/Kendu Bay Town',
            'Rangwe/West Gem', 
            'Rangwe/East Gem',
            'Rangwe/Kagan',
            'Rangwe/Kochia',
            'Homa Bay Town/Homa Bay Central',
            'Homa Bay Town/Homa Bay Arujo',
            'Homa Bay Town/Homa Bay West ward',
            'Homa Bay Town/Homa Bay Eest',
            'Ndhiwa/Kwabwai',
            'Ndhiwa/Kanyidoto',
            'Ndhiwa/Kanyikela',
            'Ndhiwa/Kabouch North',
            'Ndhiwa/Kabuoch South/Pala',
            'Ndhiwa/Kanyamwa Kologi',
            'Ndhiwa/Kanyamwa Kosewe',
            'Mbita/Mafangano',
            'Mbita/Rusinga Island',
            'Mbita/Kasgunga',
            'Mbita/Gembe',
            'Mbita/Lambwe',
            'Gwasi/Gwassi West',
            'Gwasi/Gwassi North',
            'Gwasi/Gwassi South',
            'Gwasi/Ruma Kakisingiri East'
        ),
		'KE10' => array(
            'Olkeri',
            'Ongata Rongai',
            'Nkaimuranya',
            'Oloolua',
            'Ngong',
            'Kajiado Central',
            'Purko',
            'Matapato',
            'Ildamat',
            'Dalalekutuk',
            'Kaputiei North',
            'Kitengela',
            'Sholinke',
            'Kenyawa Poka',
            'Imaroro',
            'Keekonyokie',
            'Iloodokilani',
            'Magadi',
            'Ewuaso Oo Nkidong\'I',
            'Mosiro',
            'Eselenkei',
            'Entonet',
            'Kuku',
            'Rombo',
            'Kimana'
        ),
		'KE11' => array(
            'Lugari/Mautuma',
            'Lugari/Lugari Marakusi',
            'Lugari/Lumakanda',
            'Lugari/Chekalini',
            'Lugari/Chevaywa',
            'Lugari/Lwandeti',
            'Likuyani/Likuyani',
            'Likuyani/Sango',
            'Likuyani/Kongoni',
            'Likuyani/Nzoia',
            'Likuyani/Sinoko',
            'Malava/West Kabras',
            'Malava/Chemuche',
            'Malava/East Kabras',
            'Malava/Butali/Chegulo',
            'Malava/Manda Shivanga',
            'Malava/Shirugu Mugai',
            'Malava/South Kabras',
            'Lurambi/East Butsotso',
            'Lurambi/South Butsotso',
            'Lurambi/Central Butsotso',
            'Lurambi/Sheywe',
            'Lurambi/Mahiakalo',
            'Lurambi/Shirere',
            'Navakholo/Shinoyi Shikomari Esumeyia',
            'Navakholo/Ingotse Matiha',
            'Navakholo/Bunyala Central',
            'Navakholo/Bunyala East',
            'Navakholo/Bunyala West',
            'Mumias/Mumias Central Ward',
            'Mumias/Mumias North Ward',
            'Mumias/Etenje',
            'Mumias/Musanda',
            'Mumias East/Lusheya Lubinu Makunga Ward',
            'Mumias East/Khaunga Malaha Isongo Ward',
            'Mumias East/East Wanga Ward',
            'Matungu/Koyonzo',
            'Matungu/Kholera',
            'Matungu/Khalaba',
            'Matungu/Mayoni',
            'Matungu/Namamali',
            'Butere/Marama West',
            'Butere/Marama Central',
            'Butere/Marenyo  Shianda',
            'Butere/Marama North',
            'Butere/Marama South',
            'Khwisero/Kisa Central',
            'Khwisero/Kisa North',
            'Khwisero/Kisa South Kisa East',
            'Khwisero/Kisa West',
            'Shinyalu/Isukha North',
            'Shinyalu/Murhanda',
            'Shinyalu/Isukha Central',
            'Shinyalu/Isukha South',
            'Shinyalu/Isukha East',
            'Shinyalu/Isukha West',
            'Ikolomani/Idakho North',
            'Ikolomani/Idakho Central',
            'Ikolomani/Idakho East',
            'Ikolomani/Idakho South',
        ),
		'KE12' => array(
            'Kipkelion East/Londiani',
            'Kipkelion East/Kedowa',
            'Kipkelion East/Chepseon',
            'Kipkelion East/Tendeno',
            'Kipkelion West/Kunyak',
            'Kipkelion West/Kimasian',
            'Kipkelion West/Kipkelion',
            'Kipkelion West/Chilchila',
            'Ainamoi/Kapsoit',
            'Ainamoi/Ainamoi',
            'Ainamoi/Kapkugerwet',
            'Ainamoi/Kipchebor',
            'Ainamoi/Kipchimchim',
            'Ainamoi/Kapsaos',
            'Bureti/Roret/Kisiara',
            'Bureti/Tebesonik',
            'Bureti/Cheborge/Cheboin',
            'Bureti/Chemosot',
            'Bureti/Litein',
            'Bureti/Cheplanget',
            'Bureti/Kapkatet',
            'Belgut/Waldai',
            'Belgut/Kabianga',
            'Belgut/Seretut',
            'Belgut/Chalk',
            'Belgut/Kapsuseer',
            'Sigowet/Sigowet',
            'Sigowet/Soin',
            'Sigowet/Kaplelartet',
            'Sigowet/Soliat'
        ),
		'KE13' => array(
            'Gatundu South/Kiamwangi',
            'Gatundu South/Kiganjo',
            'Gatundu South/Ndarugo',
            'Gatundu South/Ngenda',
            'Gatundu North/Gituamba',
            'Gatundu North/Githobokoni',
            'Gatundu North/Chania',
            'Gatundu North/Mang’U',
            'Juja/Murera',
            'Juja/Theta',
            'Juja/Juja',
            'Juja/Witeithie',
            'Juja/Kalimoni',
            'Thika Town/Township',
            'Thika Town/Kamenu',
            'Thika Town/Hospital',
            'Thika Town/Gatuanyaga',
            'Thika Town/Ngoliba',
            'Ruiru/Biashara',
            'Ruiru/Gitothua',
            'Ruiru/Gatongora',
            'Ruiru/Kahawa/Sukari',
            'Ruiru/Kahawa Wendani',
            'Ruiru/Kiuu',
            'Ruiru/Mwiki',
            'Ruiru/Mwihoko',
            'Githunguri/Githunguri',
            'Githunguri/Githiga',
            'Githunguri/Ikinu',
            'Githunguri/Kimothai/Ngemwa Ward',
            'Githunguri/Komothai',
            'Kiambu/Ting\'Ang\'A',
            'Kiambu/Ndumberi',
            'Kiambu/Township',
            'Kiambu/Riabai',
            'Kiambaa/Cianda',
            'Kiambaa/Karuri',
            'Kiambaa/Ndenderu',
            'Kiambaa/Muchatha',
            'Kiambaa/Kihara',
            'Kabete/Gitaru',
            'Kabete/Muguga',
            'Kabete/Nyadhuna',
            'Kabete/Kabete',
            'Kabete/Uthiru',
            'Kikuyu/Karai',
            'Kikuyu/Nachu',
            'Kikuyu/Sigona',
            'Kikuyu/Kikuyu',
            'Kikuyu/Kinoo',
            'Limuru/Bibirioni',
            'Limuru/Limuru Central',
            'Limuru/Ndeiya',
            'Limuru/Limuru East',
            'Limuru/Ngecha',
            'Lari/Kinale',
            'Lari/Kijabe',
            'Lari/Nyanduma',
            'Lari/Gatamaiyo',
            'Lari/Kirenga'
        ),
		'KE14' => array(
            'Kilifi North/Kilifi North',
            'Kilifi North/Tezo Ward',
            'Kilifi North/Hospital/Sokoni',
            'Kilifi North/Kibarani',
            'Kilifi North/Dabaso',
            'Kilifi North/Matsangoni',
            'Kilifi North/Watamu',
            'Kilifi South/Kilifi South',
            'Kilifi South/Junju',
            'Kilifi South/Mwarakaya',
            'Kilifi South/Mnarani',
            'Kilifi South/Shimo La Tewa',
            'Kilifi South/Chasimba',
            'Kilifi South/Mtepeni',
            'Kaloleni/Kaloleni',
            'Kaloleni/Mariakani Ward',
            'Kaloleni/Kayafungo Ward',
            'Kaloleni/Kaloleni Ward',
            'Kaloleni/Mwanamwinga',
            'Rabai/Rabai',
            'Rabai/Mwawesa Ward',
            'Rabai/Ruruma Ward',
            'Rabai/Jibana Ward',
            'Rabai/Rabai Ward',
            'Ganze/Ganze',
            'Ganze/Dungicha',
            'Ganze/Bamba',
            'Ganze/Jaribuni',
            'Ganze/Sokoke',
            'Malindi/Malindi',
            'Malindi/Jilore',
            'Malindi/Kakuyuni',
            'Malindi/Ganda',
            'Malindi/Malindi Town',
            'Malindi/Shella Ward',
            'Magarini/Magarini',
            'Magarini/Marafa Ward',
            'Magarini/Magarini Ward',
            'Magarini/Gongoni Ward',
            'Magarini/Adu',
            'Magarini/Sabaki',
            'Magarini/Garashi Ward'
        ),
		'KE16' => array(
            'Bonchari/Bomariba/Bogi Akumu',
            'Bonchari/Bogiakumu',
            'Bonchari/Bokeira/Insaria',
            'Bonchari/Riana/Iyabe',
            'South Mugirango/Tahaka',
            'South Mugirango/Boikanga',
            'South Mugirango/Bogetenga',
            'South Mugirango/Borabu/Chitago',
            'South Mugirango/Moticho',
            'South Mugirango/Getenga',
            'Bomachoge Borabu/Boochi Masaba',
            'Bomachoge Borabu/Boochi Borabu',
            'Bomachoge Borabu/Bokimonge',
            'Bomachoge Borabu/Magenche',
            'Bobasi/Masige West',
            'Bobasi/Masige East',
            'Bobasi/Basi Central',
            'Bobasi/Nyachekl',
            'Bobasi/Bassi Bogetaorio',
            'Bobasi/Bobasi Chache',
            'Bobasi/Sameta/Mokwerero',
            'Bobasi/Bobasi/Boitangare',
            'Bomachoge Chache/Majoge Basi',
            'Bomachoge Chache/Boochi/Tendere',
            'Bomachoge Chache/Bositi/Sengea',
            'Nyaribari Masaba/Ichuni',
            'Nyaribari Masaba/Nyamasibi',
            'Nyaribari Masaba/Masimby',
            'Nyaribari Masaba/Gesusu',
            'Nyaribari Masaba/Mobamba/Kiamokama',
            'Nyaribari Chache/Bosongo/Kiogoro',
            'Nyaribari Chache/Kisii Central',
            'Nyaribari Chache/Keumbu',
            'Nyaribari Chache/Kiogoro',
            'Nyaribari Chache/Birongo',
            'Nyaribari Chache/Ibeno',
            'Kitutu Chache North/Monyerero',
            'Kitutu Chache North/Sensi',
            'Kitutu Chache North/Marani',
            'Kitutu Chache North/Mwamonari',
            'Kitutu Chache South/Bogusero',
            'Kitutu Chache South/Bogeka',
            'Kitutu Chache South/Nyakoe',
            'Kitutu Chache South/Kitutu Central',
            'Kitutu Chache South/Nyatieko'
        ),
		'KE17' => array(
            'Kisumu East/Mkendwa/Kajulu',
            'Kisumu East/Manyatta B',
            'Kisumu East/Kolwa East',
            'Kisumu East/Nyalenda A',
            'Kisumu East/Manyatta/Kolwa Central',
            'Kisumu West/South West',
            'Kisumu West/Central Kisumu',
            'Kisumu West/Kisumu North',
            'Kisumu West/West Kisumu',
            'Kisumu West/North West Kisumu',
            'Kisumu Central/Railways',
            'Kisumu Central/Migosi',
            'Kisumu Central/Shauri Moyo Kaloleni',
            'Kisumu Central/Market Milimani',
            'Kisumu Central/Kondele',
            'Kisumu Central/Nyalenda B',
            'Seme/West Seme',
            'Seme/Central Seme',
            'Seme/North Seme',
            'Seme/East Seme',
            'Nyando/East Kano/Wawidhi',
            'Nyando/Awasi',
            'Nyando/Ahero',
            'Nyando/Kabonyo',
            'Nyando/Kobura',
            'Muhoroni/Miwani',
            'Muhoroni/Ombeyi',
            'Muhoroni/Masogo',
            'Muhoroni/Chemelil',
            'Muhoroni/Muhoroni Township',
            'Nyakach/South West Nyakach',
            'Nyakach/North  Nyakach',
            'Nyakach/Central Nyakach',
            'Nyakach/West Nyakach',
            'Nyakach/South Eest Nyakach'
        ),
		'KE18' => array(
            'Tseikuru',
			'Ngomeni',
			'Mumoni',
			'Tharaka',
			'Kyuso',
			'Kyome',
			'Nguutani',
			'Migwani',
			'Kiomo',
			'Central',
			'Kivou',
			'Nguni',
			'Nuu',
			'Mui',
			'Waita',
			'Eastern',
			'Kauwi',
			'Central',
			'North',
			'Kisasi',
			'Mbitini',
			'Yatta',
			'Kanyangi',
			'Miambani',
			'Kyangwithya West',
			'Township',
			'Mulango',
			'Kyangwithya East',
			'Kitui East',
			'Zombe',
			'Nzambani',
			'Chuluni',
			'Voo',
			'Endau',
			'Mutitu',
			'Mutha/Ndakaini',
			'Mutumo/Kibwea',
			'Ikaanga/Kyatune',
			'Kanziko/Simisi',
			'Ikuutha/Kasaala',
			'Athi/Muluma/Kilivu'
        ),
		'KE19' => array(
            'Msambweni/Msambweni',
            'Msambweni/Gombato Bongwe Ward',
            'Msambweni/Ukunda Ward',
            'Msambweni/Kinondo',
            'Msambweni/Ramisi',
            'Msambweni/Pongwe Kidimu/Kigwed E Ward',
            'Lunga Lunga/Lunga Lunga',
            'Lunga Lunga/Dzombo Ward',
            'Lunga Lunga/Pongwe',
            'Lunga Lunga/Vanga Ward',
            'Lunga Lunga/Mwereni',
            'Matuga/Matuga',
            'Matuga/Waa Ward',
            'Matuga/Tsimba Golini',
            'Matuga/Tiwi/Mazumalu Me Ward',
            'Matuga/Kubo South/Mangawa Ni',
            'Matuga/Mwalupamba Mkongani Ward',
            'Kinango/Kinango',
            'Kinango/Ndavaya Ward',
            'Kinango/Puma',
            'Kinango/Kinango Ward',
            'Kinango/Mackinon Road Ward',
            'Kinango/Chengoni/Samb Uru Ward',
            'Kinango/Mwavumbo Ward',
            'Kinango/Kasemeni Ward',
        ),
		'KE20' => array(
            'Laikipia West/Ol Moran',
            'Laikipia West/Rumuruti Township',
            'Laikipia West/Githiga',
            'Laikipia West/Marmanet',
            'Laikipia West/Igwamiti',
            'Laikipia West/Salama',
            'Laikipia East/Laikipia East',
            'Laikipia East/Ngobit',
            'Laikipia East/Thingithu',
            'Laikipia East/Tigithi',
            'Laikipia East/Nanyuki',
            'Laikipia East/Umande',
            'Laikipia North/Laikipia North',
            'Laikipia North/Sosian',
            'Laikipia North/Segera',
            'Laikipia North/Mugogodo West',
            'Laikipia North/Mugogodo East'
        ),
		'KE22' => array(
            'Kangundo/Kangundo North',
            'Kangundo/Kangundo Central',
            'Kangundo/Kangundo East',
            'Kangundo/Kangundo West',
            'Matungulu/Matungulu North',
            'Matungulu/Tela',
            'Matungulu/Matungulu East',
            'Matungulu/Matungulu West',
            'Matungulu/Kyeleni',
            'Kathiani/Mitaboni/Math Unga',
            'Kathiani/Kathiani',
            'Kathiani/Kaewa',
            'Kathiani/Iveti/Kaani',
            'Mavoko/Athi River Township',
            'Mavoko/Syokimau',
            'Mavoko/Sophia Kmc/Kinanie',
            'Mavoko/Muthuwani/Kat',
            'Machakos Town/Kalama/Kyangal/Kimutua',
            'Machakos Town/Machakos Central',
            'Machakos Town/Ngelani/Mutituni/Mua',
            'Machakos Town/Mutituni',
            'Machakos Town/Mumbuni North',
            'Machakos Town/Muvuti/Kiima Kimwe',
            'Machakos Town/Muumando/Kola',
            'Mwala/Kathama/Mbiuni',
            'Mwala/Mwala/Makutan O/Mango',
            'Mwala/Masii/Vyulya',
            'Mwala/Muthetheni/Miu',
            'Mwala/Wamunyu/Yathui',
            'Mwala/Kibauni/Ikalaasa'
        ),
		'KE23' => array(
            'Mbooni/Mbooni',
            'Mbooni/Tulimani',
            'Mbooni/Kisau',
            'Mbooni/Kithungo/Kitundu',
            'Mbooni/Kalawa',
            'Mbooni/Kako',
            'Kilome/Kasikeu',
            'Kilome/Mukaa',
            'Kilome/Kim A Kiu',
            'Kaiti/Ukia/Iuani',
            'Kaiti/Kilungu',
            'Kaiti/Ilima',
            'Kaiti/Watema/Kee/Kivani',
            'Makueni/Kitise',
            'Makueni/Wote',
            'Makueni/Kathonzweni',
            'Makueni/Mavindini',
            'Makueni/Kikumini',
            'Makueni/Nguu',
            'Makueni/Emali',
            'Makueni/Nzaui',
            'Makueni/Mbitini',
            'Kibwezi West/Makindu',
            'Kibwezi West/Nguumo',
            'Kibwezi West/Kikumbulyu',
            'Kibwezi East/Nguumo/Makindu',
            'Kibwezi East/Masongaleni/Ngwata',
            'Kibwezi East/Mitito Andei',
            'Kibwezi East/Thange',
            'Kibwezi East/Nzambani',
        ),
		'KE26' => array(
            'Igembe South/Athiru Gaiti',
            'Igembe South/Kanuni',
            'Igembe South/Akachiu',
            'Igembe South/Maua Town',
            'Igembe South/Kiegoi',
            'Igembe Central/Athuri Runjine',
            'Igembe Central/Igembe East',
            'Igembe Central/Kangeta',
            'Igembe Central/Akirang\'Ondu',
            'Igembe Central/Njai',
            'Igembe North/Amuathi',
            'Igembe North/Antuambui',
            'Igembe North/Antuabetwe Kiongo',
            'Igembe North/Naathu',
            'Igembe North/Ntunene',
            'Tigania West/Athwana',
            'Tigania West/Kianjai',
            'Tigania West/Akithii',
            'Tigania West/Mbeu',
            'Tigania West/Nkomo',
            'Tigania East/Thangatha',
            'Tigania East/Karama',
            'Tigania East/Kiguchwa',
            'Tigania East/Mikinduri',
            'Tigania East/Muthara',
            'North Imenti/Municipality',
            'North Imenti/Ntima East',
            'North Imenti/Ntima West',
            'North Imenti/Nyaki West',
            'North Imenti/Nyaki East',
            'Mbuuri/Timau',
            'Mbuuri/Kisima',
            'Mbuuri/Naari',
            'Mbuuri/Ruiri',
            'Central Imenti/Kiagu',
            'Central Imenti/Mwangathia',
            'Central Imenti/Abothuguchi Central',
            'Central Imenti/Kibirichia',
            'Central Imenti/Abothuguchi West',
            'South Imenti/Mitunguu',
            'South Imenti/Igoji East',
            'South Imenti/Abogeta East',
            'South Imenti/Igoji West',
            'South Imenti/Abogeta West',
            'South Imenti/Nkuene'
        ),
		'KE27' => array(
            'Rongo/North Kamagambo',
            'Rongo/Central Kamagambo',
            'Rongo/East Kamagambo',
            'Rongo/South Kamagambo',
            'Awendo/Awendo',
            'Awendo/North East Sakwa',
            'Awendo/South Sakwa',
            'Awendo/West Sakwa',
            'Awendo/Central Sakwa',
            'Migori East/Migori East',
            'Migori East/God Jope',
            'Migori East/Suna Central',
            'Migori East/Kakrao',
            'Migori East/Kwa',
            'Migori West/Migori West',
            'Migori West/Wiga',
            'Migori West/Nyabisawa',
            'Migori West/Suna Town',
            'Migori West/Giribe',
            'Uriri/Uriri',
            'Uriri/West Kanyamkago',
            'Uriri/Uriri',
            'Uriri/Central Kanyamkago',
            'Uriri/South Kanyamkago',
            'Uriri/East Kanyamkago',
            'Nyatike/Nyatike',
            'Nyatike/Kachieng',
            'Nyatike/Kanyasa',
            'Nyatike/North Kadem',
            'Nyatike/Macalder',
            'Nyatike/Kaler',
            'Nyatike/Got Kachola',
            'Nyatike/Muhuru',
            'Kuria East/Kuria East',
            'Kuria East/Bukura East',
            'Kuria East/Bukura Central/Ikerege',
            'Kuria East/Isibania',
            'Kuria East/Mokerero',
            'Kuria East/Masaba',
            'Kuria East/Tagare',
            'Kuria East/Nyamosonge/Komosoko',
            'Kuria East/Gokeharaka/ Getambwega',
            'Kuria West/Kuria West',
            'Kuria West/Ntimaru West',
            'Kuria West/Ntimaru East',
            'Kuria West/Nyabasi East',
            'Kuria West/Nyabasi West'
        ),
		'KE28' => array(
            'Changamwe/Portreitz',
            'Changamwe/Kipevu',
            'Changamwe/Airport',
            'Changamwe/Changamwe',
            'Changamwe/Chaani',
            'Jomvu/Jomvu Kuu',
            'Jomvu/Magongo',
            'Jomvu/Miritini',
            'Kisauni/Mjambere',
            'Kisauni/Junda Ward',
            'Kisauni/Bamburi',
            'Kisauni/Mwakirunge',
            'Kisauni/Magogoni',
            'Kisauni/Mtopanga',
            'Nyali/Shanzu Ward',
            'Nyali/Frere Town Ward',
            'Nyali/Maweni Ward',
            'Nyali/Nyali/Mkomani',
            'Nyali/Kongowea',
            'Nyali/Kisauni Ward',
            'Likoni/Mtongwe Ward',
            'Likoni/Shika Adabu Ward',
            'Likoni/Bofu Ward',
            'Likoni/Likoni Ward',
            'Likoni/Timbwani Ward',
            'Mvita/Mji wa Kale/Makadara Ward',
            'Mvita/Tudor',
            'Mvita/Tononoka',
            'Mvita/Shimanzi Ganjoni',
            'Mvita/Majengo Ward'
        ),
		'KE29' => array(
            'Kiharu/Wangu',
            'Kiharu/Mugoiri',
            'Kiharu/Mbiri',
            'Kiharu/Township',
            'Kiharu/Murarandia',
            'Kiharu/Gaturi',
            'Kigumo/Kahumbu',
        ),
		'KE30' => array(
			'Westlands/Kitusuru',
			'Westlands/Parklands/Highridge',
			'Westlands/Karura',
			'Westlands/Kangemi',
			'Westlands/Mountain View',
			'Dagoreti/Kilimani',
			'Dagoreti/Kawangwa Re',
			'Dagoreti/Gatina',
			'Dagoreti/Kilelesliwa',
			'Dagoreti/Kabiro',
			'Dagoretti South/Mutuini',
			'Dagoretti South/Ngando',
			'Dagoretti South/Riruta',
			'Dagoretti South/Uthiru/Rut Himitu',
			'Dagoretti South/Waithaka',
			'Langata/Karen',
			'Langata/Nairobi West',
			'Langata/Mugumo Ini',
			'Langata/South C',
			'Langata/Nyayo Highrise',
			'Kibra/Laini Saba',
			'Kibra/Lindi',
			'Kibra/Makina',
			'Kibra/Woodley',
			'Kibra/Sarang\'Ombe',
			'Kasarani/Clay City',
			'Kasarani/Mwiki',
			'Kasarani/Ngumba',
			'Kasarani/Njiru',
			'Kasarani/Ruai',
			'Roysambu/Githurai',
			'Roysambu/Kahawa',
			'Roysambu/Kahawa West',
			'Roysambu/Roysambu',
			'Roysambu/Kahawa',
			'Ruaraka/Babadogo',
			'Ruaraka/Utalii',
			'Ruaraka/Mathare North',
			'Ruaraka/Lucky Summer',
			'Ruaraka/Korogoch O',
			'Embakasi South/Imara Daima',
			'Embakasi South/Kwa Njenga',
			'Embakasi South/Kwa Reuben',
			'Embakasi South/Pipeline',
			'Embakasi South/Kware',
			'Kariobangi North/Kariobangi North',
			'Kariobangi North/Dandora Area',
			'Embakasi Central/Kayole North',
			'Embakasi Central/Kayole Central',
			'Embakasi Central/Komarock South',
			'Embakasi Central/Komarock',
			'Embakasi Central/Matopeni', 
			'Embakasi East/Upper Savanna',
			'Embakasi East/Lower Savanna',
			'Embakasi East/Embakasi',
			'Embakasi East/Utawala',
			'Embakasi East/Mihango',
			'Embakasi West/Umoja',
			'Embakasi West/Mowlem',
			'Embakasi West/Kariobangi South',
			'Makadara/Maringo/Hamza',
			'Makadara/Viwandani',
			'Makadara/Harambee',
			'Makadara/Makongeni',
			'Kamukunji/Pumwani',
			'Kamukunji/Eastleigh North',
			'Kamukunji/Eastleigh South',
			'Kamukunji/Airbase',
			'Kamukunji/Califormia',
			'Starehe/Nairobi Central',
			'Starehe/Ngara',
			'Starehe/Pangani',
			'Starehe/Ziwani/Kar Iokor',
			'Starehe/Landimawe',
			'Starehe/Nairobi South',
			'Mathare/Hospital',
			'Mathare/Mabitini',
			'Mathare/Huruma',
			'Mathare/Ngei',
			'Mathare/Miango Kubwa',
			'Mathare/Kiamaiko'
        ),
		'KE31' => array(
            'Njoro/Mau Narok',
            'Njoro/Mauche',
            'Njoro/Kihingo',
            'Njoro/Nesuit',
            'Njoro/Lare',
            'Njoro/Njoro',
            'Naivasha/Biashara',
            'Naivasha/Hellsgate',
            'Naivasha/Lake View',
            'Naivasha/Mai Mahiu',
            'Naivasha/Maeilla',
            'Naivasha/Olkaria',
            'Naivasha/Naivasha East',
            'Naivasha/Viwanda',
            'Gilgil/Gilgil',
            'Gilgil/Elementaita',
            'Gilgil/Mbaruk',
            'Gilgil/Malewa West',
            'Gilgil/Murindat',
            'Kuresoi South/Amalo',
            'Kuresoi South/Keringet',
            'Kuresoi South/Kiptagit',
            'Kuresoi South/Tinet',
            'Kuresoi North/Kiptororo',
            'Kuresoi North/Nyota',
            'Kuresoi North/Sirikwa',
            'Kuresoi North/Kamara',
            'Subukia/Waseges',
            'Subukia/Subukia',
            'Subukia/Kabazi/Mogamano',
            'Rongai/Menegai West',
            'Rongai/Soin',
            'Rongai/Visoi',
            'Rongai/Mosop',
            'Rongai/Solai',
            'Bahati/Dundori',
            'Bahati/Kabatini',
            'Bahati/Kiamaina',
            'Bahati/Lanet/Umoja',
            'Bahati/Bahati',
            'Nakuru Town West/Barut',
            'Nakuru Town West/London',
            'Nakuru Town West/Kaptembwa',
            'Nakuru Town West/Kapkures',
            'Nakuru Town West/Rhoda',
            'Nakuru Town West/Shaabab',
            'Nakuru Town East/Bisashara',
            'Nakuru Town East/Kivunbini',
            'Nakuru Town East/Flamingo',
            'Nakuru Town East/Menengai',
            'Nakuru Town East/Nakuru East'
        ),
		'KE32' => array(
            'Nandi Hills/Nandi Hills',
            'Nandi Hills/Chepkunyuk',
            'Nandi Hills/Chemelil',
            'Nandi Hills/Kapsimatwo',
            'Mosop/Mosop',
            'Mosop/Chepterwai',
            'Mosop/Kipkaren',
            'Mosop/Kebulonik/Kurgung',
            'Mosop/Kabiyet',
            'Mosop/Ndalat',
            'Mosop/Kabisaga',
            'Mosop/Sangalo'
        ),
		'KE33' => array(
            'Kilgoris/Kilgoris Central',
            'Kilgoris/Keyian',
            'Kilgoris/Angata Barikoi',
            'Kilgoris/Shankoe',
            'Kilgoris/Kimintet',
            'Emurua Dikirr/Mogondo',
            'Emurua Dikirr/Ilkerin',
            'Emurua Dikirr/Ololmongo',
            'Emurua Dikirr/Kapsasian',
            'Narok North/Narok Town',
            'Narok North/Olposimuru',
            'Narok North/Olokurto',
            'Narok North/Olorropil',
            'Narok North/Nkareta',
            'Narok North/Melili',
            'Narok East/Mosiro',
            'Narok East/Ildamat',
            'Narok East/Keekonyokie',
            'Narok East/Suswa',
            'Narok South/Naroosura',
            'Narok South/Naikara',
            'Narok South/Loita',
            'Narok South/Sogoo',
            'Narok South/Melelo',
            'Narok South/Ololulung\'S',
            'Narok South/Sagamian',
            'Narok West/Siana',
            'Narok West/Illmotiook',
            'Narok West/Mara',
            'Narok West/Naikarra'
        ),
		'KE34' => array(
            'Kitutu Masaba/Rigoma',
            'Kitutu Masaba/Gachuba',
            'Kitutu Masaba/Kemera',
            'Kitutu Masaba/Magombo',
            'Kitutu Masaba/Manga',
            'Kitutu Masaba/Gesima',
            'West Mugirango/Nyamaiya',
            'West Mugirango/Bogichora',
            'West Mugirango/Bosamaro',
            'West Mugirango/Bonyamatutua',
            'West Mugirango/Township',
            'North Mugirango/Itibo',
            'North Mugirango/Bomwagamo',
            'North Mugirango/Bokeria',
            'North Mugirango/Magwagwa',
            'North Mugirango/Ekerenyo',
            'Borabu/Mekenene',
            'Borabu/Kiabonyoru',
            'Borabu/Nyansiongo',
            'Borabu/Esisie'
        ),
		'KE36' => array(
            'Tetu/Dedan Kimathi',
            'Tetu/Wamagana',
            'Tetu/Gaaki',
            'Kieni/Mweiga',
            'Kieni/Naromoru',
            'Kieni/Mwiyogo',
            'Kieni/Mugunda',
            'Kieni/Gatarakwa/Muganda',
            'Kieni/Thegu River',
            'Kieni/Kabaru',
            'Kieni/Gakawa',
            'Mathira/Ruguru',
            'Mathira/Magutu',
            'Mathira/Iriani',
            'Mathira/Konyu',
            'Mathira/Kirimukuyu',
            'Mathira/Karatina Town',
            'Othaya/Mahiga',
            'Othaya/Iriani',
            'Othaya/Chiga',
            'Othaya/Karima',
            'Mukurweini/Gikondi/Ru Tune',
            'Mukurweini/Rugi',
            'Mukurweini/Mukurwe Ini West',
            'Mukurweini/Mukurwe Ini Central',
            'Nyeri Town/Mathari/Kiganjo',
            'Nyeri Town/Rware',
            'Nyeri Town/Gatitu/Muruguru',
            'Nyeri Town/Ruring\’U',
            'Nyeri Town/Kamakwa',
        ),
		'KE38' => array(
            'Ugenya/West Ugenya',
            'Ugenya/Ukwala',
            'Ugenya/North Ugenya',
            'Ugenya/East Ugenya',
            'Ugunja/Sidindi',
            'Ugunja/Sigomere',
            'Ugunja/Ugunja',
            'Alego Usonga/Usonga',
            'Alego Usonga/West Alego',
            'Alego Usonga/Central Alego',
            'Alego Usonga/Siaya Township',
            'Alego Usonga/North Alego',
            'Alego Usonga/South East Alego',
            'Gem/North Gem',
            'Gem/West Gem',
            'Gem/Central Gem',
            'Gem/Yala Township',
            'Gem/East Gem',
            'Gem/South Gem',
            'Bondo/West Yimbo',
            'Bondo/Central Sakwa',
            'Bondo/South Sakwa',
            'Bondo/Yimbo East',
            'Bondo/West Sakwa',
            'Rarieda/East Asembo',
            'Rarieda/West Asembo',
            'Rarieda/North Uyoma',
            'Rarieda/South Uyoma',
            'Rarieda/West Uyoma'
        ),
		'KE39' => array(
            'Taveta/Chala Ward',
            'Taveta/Mahoo',
            'Taveta/Bomani',
            'Taveta/Mboghoni Ward',
            'Taveta/Mata Ward',
            'Wundanyi/Wundanyi Ward',
            'Wundanyi/Werugha',
            'Wundanyi/Wumingu',
            'Wundanyi/Mwanda',
            'Mwatate/Ronge Ward',
            'Mwatate/Mwatate Ward',
            'Mwatate/Bura Ward',
            'Mwatate/Chawia Ward',
            'Voi/Mbololo Ward',
            'Voi/Sagala Ward',
            'Voi/Kaloleni',
            'Voi/Marungu Ward',
            'Voi/Kasigau Ward',
            'Voi/Ngolia Ward',
        ),
		'KE41' => array(
            'Igambang\'Ombe/Mariani',
            'Igambang\'Ombe/Karingani',
            'Igambang\'Ombe/Mugumoni',
            'Igambang\'Ombe/Mugwe',
            'Igambang\'Ombe/Igambang\'Ombe',
            'Maara/Mwimbi',
            'Maara/Ganga',
            'Maara/Mitheru/Muthambi'
        ),
		'KE42' => array(
            'Kwanza/Keiyo',
            'Kwanza/Kwanza',
            'Kwanza/Kapomboi',
            'Kwanza/Bidii',
            'Endebess/Chepchoina',
            'Endebess/Endebess',
            'Endebess/Matumbei',
            'Saboti/Kinyoro',
            'Saboti/Matisi',
            'Saboti/Tuwani',
            'Saboti/Saboti',
            'Saboti/Machewa',
            'Saboti/Sikhendu',
            'Saboti/Nabiswa',
            'Kiminini/Kiminini',
            'Kiminini/Waltaluk',
            'Kiminini/Sirende',
            'Kiminini/Hospital',
            'Cherangani/Sinyerere',
            'Cherangani/Sitatunga',
            'Cherangani/Makutano',
            'Cherangani/Kaplainai',
            'Cherangani/Motosiet',
            'Cherangani/Cherangani',
            'Cherangani/Chepsiro'
        ),
		'KE44' => array(
            'Soy/Kadiwa/Kapsuswa',
            'Soy/Soy',
            'Soy/Kipsomba',
            'Soy/Koisagat',
            'Soy/Ziwa',
            'Soy/Kapkures',
            'Soy/Moi\'s Brigde',
            'Soy/Barsombe',
            'Turbo/Ngenyilel',
            'Turbo/Tapsagoi',
            'Turbo/Kamagut',
            'Turbo/Kiplombe',
            'Turbo/Kapsaos',
            'Moiben/Karuma/Meibeki',
            'Moiben/Moiben',
            'Moiben/Sergoit',
            'Moiben/Tembelio',
            'Moiben/Kimumu',
            'Ainabkoi/Kapsoya',
            'Ainabkoi/Kaptagat',
            'Ainabkoi/Ainabkoi/Olare',
            'Kapseret/Simat/Kapseret',
            'Kapseret/Kipkenyo',
            'Kapseret/Ngeria',
            'Kapseret/Megun',
            'Kapseret/Langas',
            'Tarakwa/Racecourse',
            'Tarakwa/Cheptiret/Kipchamo',
            'Tarakwa/Tulwet/Chiyat',
            'Tarakwa/Tarakwa'
        ),
		'KE45' => array(
            'Vihiga/Lugaga Wamuluma',
            'Vihiga/South Maragoli',
            'Vihiga/Central Maragoli',
            'Vihiga/Mungoma',
            'Sabatia/Lyaduywa/Izava',
            'Sabatia/West Sabatia',
            'Sabatia/Chavakali',
            'Sabatia/North Maragoli',
            'Sabatia/Wodanga',
            'Sabatia/Busali',
            'Hamisi/Shiru',
            'Hamisi/Gisambai',
            'Hamisi/Shamakhok Ho',
            'Hamisi/Banja',
            'Hamisi/Muhudu',
            'Hamisi/Tambua',
            'Hamisi/Jepkoyai',
            'Emuhaya/Emuhaya',
            'Emuhaya/West Bunyore',
            'Emuhaya/Central Bunyore',
            'Emuhaya/East Bunyore',
            'Luanda/Luanda',
            'Luanda/Wemilabi',
            'Luanda/Mwibona',
            'Luanda/Luanda South',
            'Luanda/Emabungo',
        ),
		'KE47' => array(
            'Riwo',
            'Endugh',
            'Mnagei',
            'Siyoi',
            'Kapenguria'
        ),
    );
    return $cities;
}

/**
* @snippet Remove the Postcode Field on the WooCommerce Checkout
* @author Fred Peng
* @email fred.peng10@gmail.com
*/
 
add_filter('woocommerce_checkout_fields' , 'sophie_remove_billing_postcode_checkout');
 
function sophie_remove_billing_postcode_checkout($fields) {
  unset($fields['billing']['billing_postcode']);
  return $fields;
}

/**
* @snippet Remove the Company Field on the WooCommerce Checkout
* @author Fred Peng
* @email fred.peng10@gmail.com
*/

add_filter('woocommerce_checkout_fields' , 'sophie_remove_billing_company_checkout');

function sophie_remove_billing_company_checkout($fields) {
  unset($fields['billing']['billing_company']);
  return $fields;
}

/**
* @snippet Remove the Company Field on the WooCommerce Checkout
* @author Fred Peng
* @email fred.peng10@gmail.com
*/

add_filter('woocommerce_checkout_fields' , 'sophie_remove_billing_address_2_checkout');

function sophie_remove_billing_address_2_checkout($fields) {
  unset($fields['billing']['billing_address_2']);
  return $fields;
}

/**
* @snippet Remove the ADDITIONAL INFORMATION Field on the WooCommerce Checkout
* @author Fred Peng
* @email fred.peng10@gmail.com
*/

add_filter('woocommerce_enable_order_notes_field', '__return_false');

/**
* @snippet Reorder the fields on the WooCommerce Checkout
* @author Fred Peng
* @email fred.peng10@gmail.com
*/

add_filter("woocommerce_checkout_fields", "custom_override_checkout_fields");

function custom_override_checkout_fields($fields) {
    $fields['billing']['billing_first_name']['priority'] = 10;
    $fields['billing']['billing_last_name']['priority'] = 20;
    $fields['billing']['billing_state']['priority'] = 50;
    $fields['billing']['billing_city']['priority'] = 60;
    $fields['billing']['billing_address_1']['priority'] = 70;
    $fields['billing']['billing_phone']['priority'] = 100;
    $fields['billing']['billing_email']['priority'] = 110;
    return $fields;
}

add_filter( 'woocommerce_default_address_fields', 'custom_override_default_locale_fields' );
function custom_override_default_locale_fields( $fields ) {
$fields['state']['priority'] = 50;
$fields['city']['priority'] = 60;
$fields['address_1']['priority'] = 70;
return $fields;
}

/**
* @snippet Checkout very slow after enable SMPT plugin.
* @author Fred Peng
* @email fred.peng10@gmail.com
*/
add_filter('woocommerce_defer_transactional_emails', '__return_true' );

// For billing and shipping fields
add_filter( 'woocommerce_default_address_fields', 'custom_default_address_fields' );
function custom_default_address_fields( $address_fields ) {
    if ( is_checkout() ) {
        $address_fields['address_1']['label'] = __('Address', 'woocommerce');
        $address_fields['address_1']['placeholder'] = __('Street and house number', 'woocommerce');
        $address_fields['country']['label'] = __('Country', 'woocommerce');
        //$address_fields['postcode']['label'] = __('Postcode', 'woocommerce');
        $address_fields['city']['label'] = __('Area', 'woocommerce');
        //$address_fields['city']['placeholder'] = __('Area', 'woocommerce');
        $address_fields['state']['label'] = __('County', 'woocommerce');
    }
    return $address_fields;
}

/*add_filter( 'woocommerce_checkout_fields', 'change_checkout_fields' );
function change_checkout_fields( $fields ) {
    $fields['order']['order_comments']['placeholder'] = __('Special notes');
    
    return $fields;
}*/

add_filter( 'woocommerce_billing_fields', 'adjust_requirement_of_checkout_contact_fields');
function adjust_requirement_of_checkout_contact_fields( $fields ) {
    //$fields['billing_phone']['required']    = false;
    $fields['billing_email']['required']    = false;

    return $fields;
}
